#! /usr/bin/env python3
# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

def configure(conf):
    # conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')
    pass

def build(bld):
    obj = bld.create_ns3_program('roit-scripts', ['core'])
    obj.source = [
        'my_scripts.cc'
        ]
    obj.env.append_value("CXXFLAGS","-I/usr/include")
    obj.env.append_value("LINKFLAGS","-L/usr/lib")

